languageCode = "en"
languageName = "English"
weight = 1
#  title = "自由法律事務所"
title = "自由" # tmp

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/logo_white.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Chū-iû Law Firm"
#  copyright = "&copy; { year } [Chū-iû Law Firm](https://www.chu-iu.pro)"
  copyright = "&copy; { year } [Chū-iû](https://www.chu-iu.pro)"

[params.author]
  name = "楊琇惠"
  image = "img/initials_white.png"
  headline = "律師"
#  bio = "A little bit about you"
  links = [
    { scale-balanced = "https://lawyerbc.moj.gov.tw/lawyer/0x0b7b30c3092fa9ae4abdcbfc80a8be1a13268d760d4fb1d74f0362608acd34ab" },
    { location-dot = "https://www.fblaw.com.tw/people/jackie-yang" },
    { linkedin = "https://www.linkedin.com/in/jackie-b-yang" },
    { email = "mailto:ish@chu-iu.pro" },
    # { phone = "tel:+886-2-2396-5918" },
  ]
