languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "自由法律事務所"
logo = "img/logo_white.png"
description = "Chū-iû Law Firm"
copyright = "&copy; { year } [Chū-iû Law Firm](https://www.chu-iu.pro/)"

dateFormat = "2014-03-18"

[author]
  name = "楊琇惠"
#   image = "img/blowfish_logo.png"
  headline = "律師"
#   bio = "A little bit about you"
  links = [
    { link = "https://lawyerbc.moj.gov.tw/lawyer/0x236a7dc239adbdb3f933ab524d318a8f942ef7a9cd562252ccb463c00b10c3e2" },
    { linkedin = "https://tw.linkedin.com/in/jackie-b-yang" },
  ]
