languageCode = "en"
languageName = "English"
weight = 1
title = "自由法律事務所"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/logo_white.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Chū-iû Law Firm"
  copyright = "&copy; { year } [Chū-iû Law Firm](https://www.chu-iu.pro/)"

[author]
  name = "楊琇惠"
#   image = "img/blowfish_logo.png"
  headline = "律師"
#   bio = "A little bit about you"
  links = [
    { scale-balanced = "https://lawyerbc.moj.gov.tw/lawyer/0x236a7dc239adbdb3f933ab524d318a8f942ef7a9cd562252ccb463c00b10c3e2" },
    { linkedin = "https://tw.linkedin.com/in/jackie-b-yang" },
  ]
